version: "3"
services:
  db:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DB}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgresql:/var/lib/postgresql/api
      - postgresql_data:/var/lib/postgresql/api/data
volumes:
  postgresql: {}
  postgresql_data: {}